name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  stage:
    name: Staging
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install linter
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s v1.24.0

    - name: Install apex/up
      run: curl -sf https://up.apex.sh/install | sudo sh

    - name: Get dependencies
      run: go mod download

    - name: Deploy
      run: make deploy

